docker:
  image: yegor256/java8
decrypt:
  settings.xml: "repo/.rultor/settings.xml.asc"
  446C141838180E001CE2448CB8F7F75FB79D276E.key: "repo/.rultor/private-keys-v1.d/446C141838180E001CE2448CB8F7F75FB79D276E.key.asc"
  C74CD4CC680C8DB53E950E80A750DCC25527E68D.key: "repo/.rultor/private-keys-v1.d/C74CD4CC680C8DB53E950E80A750DCC25527E68D.key.asc"
  pubring.kbx: "repo/.rultor/pubring.kbx.asc"
  secret.pgp: "repo/.rultor/secret.pgp.asc"
env:
  MAVEN_OPTS: -Xmx1g
  JAVA_OPTS: -Xmx1g
install: |
  sudo gem install --no-rdoc --no-ri pdd
  sudo gem install --no-rdoc --no-ri xcop
  mkdir -p ../private-keys-v1.d
  mv ../C74CD4CC680C8DB53E950E80A750DCC25527E68D.key ../private-keys-v1.d/C74CD4CC680C8DB53E950E80A750DCC25527E68D.key
  mv ../446C141838180E001CE2448CB8F7F75FB79D276E.key ../private-keys-v1.d/446C141838180E001CE2448CB8F7F75FB79D276E.key
architect:
  - smallcreep
merge:
  script: |
    pdd --file=/dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
deploy:
  script: |
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+){2}$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pcucumber-seeds -Psonar -Pqulice -Psonatype --errors --settings ../settings.xml